name: ai-plot-generator

networks:
  ai_plot_generator:
  kafka:

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        USER_UID: ${UID:-1000}
        USER_GID: ${GID:-1000}
        ENVIRONMENT: dev
    image: ai-plot-generator:local
    env_file:
      - .env
    expose:
      - 8000
    restart: on-failure
    volumes:
      - .:/app
    networks:
      - traefik
      - ai_plot_generator
      - kafka
    dns:
      - 8.8.8.8
      - 1.1.1.1
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ai_plot.rule=Host(`ai_plot.localhost`)"
      - "traefik.http.routers.ai_plot.entrypoints=web"
