"""Add scenes_count to roadmap

Revision ID: 85b20f2f75c7
Revises: da692ed35296
Create Date: 2026-09-18 11:46:53.882612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85b20f2f75c7'
down_revision: Union[str, Sequence[str], None] = 'da692ed35296'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roadmap', sa.Column('scenes_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roadmap', 'scenes_count')
    # ### end Alembic commands ###
