from typing import Protocol

from src.core.codex.models import (
    Background,
    CodexCharacter,
    Emotion,
    EmotionMatchItem,
    EmotionTags,
    Outfit,
    Sprite,
    Tag,
    Universe,
)


class CodexClientProtocol(Protocol):
    async def list_universes(self) -> list[Universe]: ...
    async def get_universe(self, universe_id: int) -> Universe: ...
    async def get_characters(self, universe_id: int) -> list[CodexCharacter]: ...
    async def get_backgrounds(self, universe_id: int) -> list[Background]: ...
    async def get_sprites(self, character_id: int) -> list[Sprite]: ...
    async def get_sprites_batch(
        self, character_ids: list[int]
    ) -> dict[int, list[Sprite]]: ...
    async def get_emotions(self, character_id: int) -> list[Emotion]: ...
    async def get_emotion_tags(self, character_id: int) -> EmotionTags: ...
    async def match_emotion(
        self, character_id: int, tags: list[str], sprite_id: int | None = None
    ) -> Emotion | None: ...
    async def match_emotions_batch(
        self, items: list[EmotionMatchItem]
    ) -> dict[int, Emotion | None]: ...
    async def get_outfits(self, sprite_id: int) -> list[Outfit]: ...
    async def get_outfit_tags(self, character_id: int) -> list[Tag]: ...
    async def match_outfit(self, sprite_id: int, tag: str) -> Outfit | None: ...
